config/routes.rb
Loveknit::Application.routes.draw do
  resources :users
  resources :patterns do
    resources :abbreviations
    resources :images
    resources :charts
    resources :chart_legends
    resources :comments
    resources :sections do
      resources :rows
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get     '/sign_up',   to: 'users#new'
  get     '/log_in',    to: 'sessions#new'
  delete  '/log_out',   to: 'sessions#destroy'

  root :to => 'sessions#new'
end

app/models/chart_legend.rb
class ChartLegend < ActiveRecord::Base
  attr_accessible :image, :pattern, :image_file_name

  belongs_to :pattern

  has_attached_file :image, :styles => { :large => "540x540", :medium => "260x260", :small => "130x130" }

  validates_presence_of :image, :pattern
end

app/controllers/chart_legends_controller.rb
class ChartLegendsController < ApplicationController
  def new
    @legend = ChartLegend.new
    @pattern = Pattern.find(params[:pattern_id])
    @legends = @pattern.chart_legends
  end

  def create
    legend = ChartLegend.new(params[:chart_legend])
    legend.pattern = Pattern.find(params[:pattern_id])
    if legend.save!
      flash[:notice] = "Legend #{legend.image_file_name} successfully added to #{legend.pattern.name}"
      redirect_to patterns_path
    else
      redirect_to new_pattern_chart_legend_path(params[:pattern_id])
    end
  end

  def destroy
    ChartLegend.destroy(params[:id])
    redirect_to patterns_path
  end
end

app/views/chart_legends/new.html.slim
.row
  .span12
    h1 New Legend for #{@pattern.name}
    .alert.alert-block You can only add one legend at a time. JPG format only.
    .alert.alert-danger Legends are presented on the PDF in the order they are uploaded.
    - if !@pattern.charts?
      = render partial: "shared/missing_charts", locals: { pattern: @pattern }

.row
  .span12
  = form_for ([@pattern, @legend]), :legend => new_pattern_chart_legend_path(@pattern), :html => { :multipart => true } do |form|
    = form.file_field :image
    p
    = form.submit "Add Legend", { class: "btn btn-success" }

.row
  .span12
    - if @legends.length > 0
      h3 Current Legends
      - @legends.each do |img|
        .row
          .span2
          .span2
            = link_to "Delete legend", pattern_chart_legend_path(pattern_id: @pattern.id, id: img.id), method: :delete, class: "btn btn-danger btn-small"
          .span8
            p = image_tag img.image(:large), { class: "thumbnail" }