config/routes.rb
Loveknit::Application.routes.draw do
  resources :users
  resources :patterns do
    resources :abbreviations
    resources :images
    resources :charts
    resources :chart_legends
    resources :comments
    resources :sections do
      resources :rows
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get     '/sign_up',   to: 'users#new'
  get     '/log_in',    to: 'sessions#new'
  delete  '/log_out',   to: 'sessions#destroy'

  root :to => 'sessions#new'
end

app/views/shared/_comment_resolve.html.slim
td #{link_to "<i class='icon-wrench'></i>".html_safe, edit_pattern_comment_path(@pattern, comment)} #{comment.resolved?}

app/views/shared/_comment_table.html.slim
td = comment.user.name
td = comment.body
td = comment.confidence
td = short_pretty_time(comment.created_at)

app/views/shared/_errors.html.slim
- if @errors
  .error
    p.label.label-warning #{@errors} Please try again!

app/views/shared/_missing_abbrevs.html.slim
.alert.alert-danger <strong>This pattern has no abbreviations.</strong> #{link_to "<i class='icon-wrench'></i> Add abbreviations".html_safe, new_pattern_abbreviation_path(pattern.id), class: "btn btn-warning"}<br> You cannot download a PDF unless abbreviations are added.

app/views/shared/_missing_charts.html.slim
small.muted
  p.text-right Charts are not required, but this pattern has no charts. <br>#{link_to "<i class='icon-ellipsis-horizontal'></i> &nbsp; Add chart".html_safe, new_pattern_chart_path(pattern), class: "btn btn-mini"}

app/views/shared/_missing_images.html.slim
.alert.alert-danger <strong>This pattern has no images.</strong> #{link_to "<i class='icon-camera'></i> &nbsp; Add images".html_safe, new_pattern_image_path(pattern), class: "btn btn-warning"}<br>You cannot download a PDF unless images are added.

app/views/shared/_missing_legend.html.slim
.alert.alert-danger <strong>This pattern has a chart but no chart legends.</strong> #{link_to "<i class='icon-key'></i> &nbsp; Add chart legends".html_safe, new_pattern_chart_legend_path(pattern), class: "btn btn-warning"}<br>You cannot download a PDF unless at least one chart legend is added.

app/views/shared/_permissions_error.html.slim
p.alert.alert-block Whoops! You don't have sufficient privileges for this.

app/views/shared/_status.html.slim
- if pattern.testing?
  span.label.label-warning.pull-right Testing
- elsif pattern.draft?
  span.label.label-info.pull-right Draft
- elsif pattern.editing?
  span.label.label-danger.pull-right Tech Editing
- else
  span.label.label-success.pull-right Published