config/routes.rb
Loveknit::Application.routes.draw do
  resources :users
  resources :patterns do
    resources :abbreviations
    resources :images
    resources :charts
    resources :chart_legends
    resources :comments
    resources :sections do
      resources :rows
    end
  end
  resources :sessions, only: [:new, :create, :destroy]

  get     '/sign_up',   to: 'users#new'
  get     '/log_in',    to: 'sessions#new'
  delete  '/log_out',   to: 'sessions#destroy'

  root :to => 'sessions#new'
end

app/models/pattern.rb
class Pattern < ActiveRecord::Base
  attr_accessible :name, :gauge, :yarn, :yarn_info, :needle, :notions, :description, :finished_sizes, :instructions, :sections_attributes, :rows_attributes, :abbreviations_attributes, :version, :chart_legends_attributes, :state, :free, :re_release, :user_id, :target_date, :errata, :errata_fixed

  has_many :sections
  has_many :rows, :through => :sections
  has_many :images
  has_many :abbreviations
  has_many :charts
  has_many :chart_legends
  has_many :comments
  belongs_to :user

  accepts_nested_attributes_for :sections
  accepts_nested_attributes_for :rows
  accepts_nested_attributes_for :abbreviations
  accepts_nested_attributes_for :charts
  accepts_nested_attributes_for :chart_legends

  # Helpers for attributes
  def images?
    return true if images.length > 0
  end

  def abbrevs?
    return true if abbreviations.length > 0
  end

  def charts?
    return true if charts.length > 0
  end

  def chart_legends?
    return true if chart_legends.length > 0
  end

  def free?
    return true unless free == nil
  end

  def comments?
    return true if comments.length > 0
  end

  # States
  def testing?
    return true if state == "testing"
  end

  def editing?
    return true if state == "editing"
  end

  def draft?
    return true if state == "draft"
  end

  def has_errors?
    return true if errata && (errata_fixed == nil || errata_fixed == "")
  end
end

app/controllers/patterns_controller.rb
class PatternsController < ApplicationController
  include AbbreviationHelper
  include PdfViewHelper
  include PatternViewHelper

  def new
    @pattern = Pattern.new
  end

  def index
    @patterns = Pattern.all
  end

  def create
    @pattern = Pattern.create(params[:pattern])
    redirect_to patterns_path
  end

  def edit
    @pattern = Pattern.find(params[:id])
  end

  def update
    @pattern = Pattern.find(params[:id])
    @pattern.update_attributes(params[:pattern])
    redirect_to patterns_path
  end

  def show
    @pattern = Pattern.find(params[:id])
  end
end

app/views/patterns/_abbreviation_fields.html.slim
table.table
  thead
    tr
      th Abbreviation
      th Definition
      th
  tbody
    tr
      td.span1 = f.text_field :stitch, class: "span12"
      td.span10 = f.text_field :definition, class: "span12"
      td.span1 = f.link_to_remove "Remove", { class: "btn btn-danger btn-mini" }

app/views/patterns/_image_fields.html.slim
= f.file_field :photo
= f.link_to_remove "Remove", { class: "btn btn-danger btn-mini" }
p

app/views/patterns/_row_fields.html.slim
table.table
  thead
    tr
      th.span1 Number
      th.span8 Instructions
      th.span1 # Sts
      th.span2
  tbody
    tr
      td = f.text_field :num, class: "span12"
      td = f.text_field :instructions, class: "span12"
      td = f.text_field :stitch_count, class: "span12"
      td = f.link_to_remove "Remove row", { class: "btn btn-danger btn-mini" }

app/views/patterns/_section_fields.html.slim
h4 Section #{f.link_to_remove "Remove section", { class: "btn btn-danger btn-mini" }}

.control-group
  = f.label :number, "Number <br><span class='muted'>Number them in order.</span>".html_safe, { class: "control-label" }
  .controls
    = f.text_field :number, class: "span1"

.control-group
  = f.label :title, "Title <br><span class='muted'>Example:<br>Set Up, Body, etc, etc.</span>".html_safe, { class: "control-label" }
  .controls
    = f.text_field :title, class: "span12"

.control-group
  = f.label :description, "Description <br><span class='muted'>Special instructions (work using smaller needles) or an introduction.</span>".html_safe, { class: "control-label" }
  .controls
    = f.text_area :description, class: "span12"

h5 Section Rows
.alert.alert-danger End each 'Instructions' box with a period. Include (RS) or (WS) with the row number for the first of each. Unless the pattern is worked in the round, then wooo, who cares?

= f.link_to_add "Add a new row", :rows, { class: "btn btn-info btn-small" }
= f.fields_for :rows

h4 Closing Intructions for Section
.control-group
  = f.label :instructions, "Instructions <br><span class='muted'>Stuff that makes more sense after ALL of the rows for this section are listed (ex: Work Rows x-y twice more).</span>".html_safe, { class: "control-label" }
  .controls
    = f.text_area :instructions, class: "span12"
hr

app/views/patterns/edit.html.slim
.row
  .span12
    h1 Edit #{@pattern.name}
    - if !@pattern.abbrevs?
      = render partial: "shared/missing_abbrevs", locals: { pattern: @pattern }
    - if !@pattern.images?
      = render partial: "shared/missing_images", locals: { pattern: @pattern }
    - if !@pattern.charts?
      = render partial: "shared/missing_charts", locals: { pattern: @pattern }
    - if (@pattern.charts? && !@pattern.chart_legends?)
      = render partial: "shared/missing_legend", locals: { pattern: @pattern }

  = nested_form_for @pattern do |f|
    table.table
      tbody
        tr
          td = f.label :name, "Pattern Name"
          td = f.text_field :name, { class: "span12"}
        tr
          td = f.label :version, "Version Number"
          td = f.text_field :version, { class: "span12"}
        tr
          td = f.label :free, "Free?"
          td = f.check_box :free, class: "span12"
        tr
          td = f.label :state, "State"
          td = f.select :state, PatternViewHelper::STATES
        tr
          td = f.label :gauge, "Gauge"
          td = f.text_field :gauge, { class: "span12"}
        tr
          td = f.label :needle, "Needle"
          td = f.text_field :needle, { class: "span12"}
        tr
          td = f.label :yarn_info, "Yarn Shown"
          td = f.text_field :yarn_info, { class: "span12"}
        tr
          td = f.label :yarn, "Yarn Requirements"
          td = f.text_field :yarn, { class: "span12"}
        tr
          td = f.label :notions, "Notions"
          td = f.text_field :notions, { class: "span12"}
        tr
          td = f.label :finished_sizes, "Finished Sizes"
          td = f.text_area :finished_sizes, { class: "span12"}
        tr
          td = f.label :description, "Description"
          td = f.text_area :description, { class: "span12"}
    hr
    h3 Abbreviations
    = f.fields_for :abbreviations
    = f.link_to_add "Add a new abbreviation", :abbreviations, { class: "btn btn-info" }

    hr
    h3 Sections
    h4.alert.alert-danger Hey! Sections and rows may not appear in order. Don't worry about that. Don't try to fix it. Just leave them in the order they've rendered on this page. If you try and re-order it, you are going to break literally everything.
    p.muted This is why the numbering was so important when you were making the sections and the rows!
    = f.fields_for :sections
    = f.link_to_add "Add a new section", :sections, { class: "btn btn-info" }

    p
    = f.submit "Update Pattern", class: "btn btn-success btn-large btn-block"

app/views/patterns/index.html.slim
h2 <i class='icon-book'></i> Pattern Library

- @patterns.each do |pattern|
  .row
    .span1
    .span2
      - if pattern_meets_pdf_requirements?(pattern)
        br
        #{link_to "<i class='icon-file'></i> &nbsp; PDF".html_safe, pattern_path(pattern, :format => "pdf"), { class: "btn btn-info" }}
      p
      - if pattern.testing?
        #{link_to "<i class='icon-thumbs-up'></i> &nbsp; Review".html_safe, pattern_comments_path(pattern), { class: "btn btn-warning" }}

      p
      - if pattern.editing?
        #{link_to "<i class='icon-strikethrough'></i> &nbsp; Tech Edit".html_safe, new_pattern_comment_path(pattern), { class: "btn btn-danger" }}

      p
      .btn-group
        a.btn.dropdown-toggle data-toggle="dropdown" href="#" <i class='icon-pencil'></i> &nbsp; Edit... <span class="caret"></span>
        ul.dropdown-menu
          li.edit-pattern = link_to "<i class='icon-pencil'></i> &nbsp; Pattern".html_safe, edit_pattern_path(pattern.id)
          li.edit-images = link_to "<i class='icon-camera'></i> &nbsp; Images".html_safe, new_pattern_image_path(pattern)
          li.edit-charts = link_to "<i class='icon-ellipsis-horizontal'></i> &nbsp; Charts".html_safe, new_pattern_chart_path(pattern)
          - if pattern.charts?
            li.edit-legends = link_to "<i class='icon-key'></i> &nbsp; Chart Legends".html_safe, new_pattern_chart_legend_path(pattern)

    .span9
      h4 #{pattern.name} <small class="pull-right">Version #{pattern.version}</small>

      = render partial: "shared/status", locals: { pattern: pattern }

      p.muted Created #{pretty_time(pattern.created_at)} &bull; Last updated #{pretty_time(pattern.updated_at)}

      small #{pattern.description}

      - if !pattern.abbrevs?
        = render partial: "shared/missing_abbrevs", locals: { pattern: pattern }
      - if !pattern.images?
        = render partial: "shared/missing_images", locals: { pattern: pattern }
      - if !pattern.charts?
        = render partial: "shared/missing_charts", locals: { pattern: pattern }
      - if (pattern.charts? && !pattern.chart_legends?)
        = render partial: "shared/missing_legend", locals: { pattern: pattern }
  hr

= link_to "Add a new pattern", new_pattern_path, { class: "btn btn-success btn-block btn-large" }

app/views/patterns/new.html.slim
.row
  .span12
    h1 Create a new pattern

    .alert.alert-block All fields are required. Syntax and grammar matter, a PDF will be generated from your input. You will have to clear the existing values to put in the information for this pattern.

    .alert.alert-error Please use the existing values as a guideline for formatting.
    hr

.row
  .span12
    h3 The Basics
    = nested_form_for(@pattern, html: { multipart: true, class: "new_model form-horizontal" } ) do |f|
      .control-group
        = f.label :name, "Pattern Name", { class: "control-label" }
        .controls
          = f.text_field :name, value: "Traveling Woman", class: "span12"

      .control-group
        = f.label :version, "Version Number", { class: "control-label" }
        .controls
          = f.text_field :version, value: "1", class: "span12"

      .control-group
        = f.label :free, "Free?", { class: "control-label" }
        .controls
          = f.check_box :free, value: "yes", class: "span12"

      .control-group
        = f.label :state, "State", { class: "control-label" }
        .controls
          = f.select :state, PatternViewHelper::STATES

      = f.label :description, "<h4>Description</h4>".html_safe
      = f.text_area :description, class: "span12", value: "This quick and easy basketweave cowl can be knit in nearly any yarn weight, and is suitable for beginning knitters. This cowl reminds me of my days spent weaving and continuously reminds me of my forgotten hobby. Worked in the round, the reversible stitch is easy to memorize or adapt to other yarn weights. Instructions are also given for an infinity cowl, which can be worn looped around your neck multiple times."

      hr
      h3 Materials
      .control-group
        = f.label :gauge, "Gauge", { class: "control-label" }
        .controls
          = f.text_field :gauge, value: "x sts/x rows per 4 in/10 cm", class: "span12"

      .control-group
        = f.label :needle, "Needle", { class: "control-label" }
        .controls
          = f.text_field :needle, value: "US 6 (4.0mm) 16 in circular", class: "span12"

      .control-group
        = f.label :yarn_info, "Yarn Shown", { class: "control-label" }
        .controls
          = f.text_field :yarn_info, value: "Company Brand (x% Fiber, x yards/x meters per x grams). Shown in color.", class: "span12"

      .control-group
        = f.label :yarn, "Yarn Requirements", { class: "control-label" }
        .controls
          = f.text_field :yarn, value: "Approximately x yards/x meters [WEIGHT] weight yarn.", class: "span12"

      .control-group
        = f.label :notions, "Notions <br><span class='muted'>List in order used</span>".html_safe, { class: "control-label" }
        .controls
          = f.text_field :notions, value: "1 stitch marker, darning needle.", class: "span12"

      hr
      = f.label :finished_sizes, "<h3>Finished Sizes</h3>".html_safe
      .alert.alert-block Separate each size with a line break.
      = f.text_area :finished_sizes, class: "span12", value: "Small: x in/x cm wingspan, x in/x cm deep."

      hr
      h3 Sections
      = f.fields_for :sections
      = f.link_to_add "Add a new section", :sections, { class: "btn btn-info" }

      hr
      = f.submit "Create Pattern", { class: "btn btn-success btn-block btn-large" }

app/views/patterns/show.html.slim
h1 #{@pattern.name}
- @pattern.images.each do |img|
  = image_tag img.photo(:large)

h3 Basic Information

p Needle: #{@pattern.needle}
p Gauge: #{@pattern.gauge}
p Yarn shown: #{@pattern.yarn_info}
p Yarn required: #{@pattern.yarn}
p Notions: #{@pattern.notions}
p Finished size(s): #{@pattern.finished_sizes}

h3 Description
p #{@pattern.description}

h3 Instructions
- @pattern.sections.each do |section|
  h4 #{section.title}
  p #{section.description}
  - section.rows.each do |row|
    p Row #{row.num} #{row.side if row.side != ""}: #{row.instructions}
  p #{section.instructions}
end